//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSL.Warehouse.CentralService.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsIgnoreList
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> AssetID { get; set; }
        public string TagId { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<bool> IsAllowed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
    }
}
