//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSL.Warehouse.CentralService.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTypeCustomerMapping
    {
        public int ID { get; set; }
        public int ATypeID { get; set; }
        public System.Guid CustomerID { get; set; }
        public Nullable<double> BillingAmount { get; set; }
        public Nullable<int> EndOfLife { get; set; }
    
        public virtual AssetTypeMaster AssetTypeMaster { get; set; }
        public virtual CustomerMaster CustomerMaster { get; set; }
    }
}
