//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSL.Warehouse.CentralService.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SerialNumber()
        {
            this.AssetMasters = new HashSet<AssetMaster>();
        }
    
        public long SID { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<long> SerialNumber1 { get; set; }
        public string TagID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.DateTime> ServerDateTime { get; set; }
        public string ChipID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetMaster> AssetMasters { get; set; }
        public virtual CustomerMaster CustomerMaster { get; set; }
    }
}
